{% set name = "mkdocstrings" %}
{% set version = "0.29.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 3657be1384543ce0ee82112c3e521bbf48e41303aa0c229b9ffcccba057d922e

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - python >={{ python_min }},<4.0
    - click >=7.0
    - jinja2 >=2.11.1
    - markdown >=3.6
    - markupsafe >=1.1
    - mkdocs >=1.6
    - mkdocs-autorefs >=1.4
    - pymdown-extensions >=6.3
    - importlib-metadata >=4.6
    - typing-extensions >=4.1

test:
  imports:
    - mkdocstrings
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  dev_url: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
