{% set name = "mkdocstrings" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings-{{ version }}.tar.gz
  sha256: 75b5cfa2039aeaf3a5f5cf0aa438507b0330ce76c8478da149d692daa7213a98

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - pdm-pep517
  run:
    - python >=3.7,<4.0
    - jinja2 >=2.11.1
    - markdown >=3.3
    - markupsafe >=1.1
    - mkdocs >=1.2
    - mkdocs-autorefs >=0.1
    - pymdown-extensions >=6.3
    - pytkdocs >=0.14.0

test:
  source_files:
    - tests
  imports:
    - mkdocstrings
    - mkdocstrings.handlers
  commands:
    - pip check
    - pytest --pyargs mkdocstrings
  requires:
    - pip
    - pytest
    - sphinx

about:
  home: https://github.com/mkdocstrings/mkdocstrings
  doc_url: https://mkdocstrings.github.io
  summary: Automatic documentation from sources, for MkDocs.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - hadim
